(in-package #:prompt-universe)

(defexpansion-plan aware-loop-transit-10
  (:intent "ten steampunk editorial variants swapping enclosed transit shells while preserving aware-loop identity")
  (:source aware-loop)
  (:preserve :primary :hair-style :title :subtitle :face-style :anatomy :denoise-ladder)
  (:variant-axes
   (:required :color-theme :theme-anchor :accessory-set)
   (:recommended :scene-shell :outfit-design :evolution-strategy :action :composition)
   (:theme-anchor-keys :secondary :background :evolution-strategy)
   (:accessory-keys :thematic-symbol))
  (:mutations
   ((:color-theme "sunset copper, cloud ivory, rose brass, sky teal, warm gold haze")
    (:secondary "open-air steam airship gondola interior, lacquered brass railing, wind-open editorial silence, minimal cloudscape framing")
    (:background "high-altitude cloud sea beyond gondola railing, soft sunset haze, distant brass fin accents, vast sky negative space")
    (:outfit-design "steampunk sky-captain couture, brass aviator collar, cloud-white layered jacket, copper strap panels, rose-gold velvet scarf tails")
    (:thematic-symbol "brass compass rose, miniature propeller charm, leather flight goggles on ribbon, sparse cloud-map scroll, copper wind dial")
    (:evolution-strategy "gear-arc geometry evolves into airship rib-curve language, brass struts echo braid loops, cloud panels align with outfit seams, graphic design fusion only, not physical mutation")
    (:action "standing at gondola railing, one hand on brass compass rose, hair and scarf lifted by gentle wind, calm skyward gaze")
    (:composition "character left against open sky, brass railing arc center, compass motif right, oversized masthead behind upper body, expansive upper negative space"))

   ((:color-theme "coal charcoal, ember amber, rust iron, smoke ivory, brass highlight")
    (:secondary "brass locomotive engine cab interior, minimal gauge wall, warm ember glow, industrial editorial silence")
    (:background "steam plume and night track blur beyond cab window, ember-lit smoke haze, sparse rail-line silhouette, dark horizon negative space")
    (:outfit-design "steampunk locomotive engineer couture, charcoal velvet coat, brass button panels, copper pipe collar, ember-orange silk neck scarf")
    (:thematic-symbol "brass throttle lever, coal shovel charm, round headlamp ring, copper steam valve wheel, sparse rail spike accent")
    (:evolution-strategy "gear-arc geometry evolves into locomotive boiler-curve language, round gauges echo loop motif, rivet bands cross outfit and cab panels, graphic design fusion only, not physical mutation")
    (:action "one hand on brass throttle lever, other hand resting on cab frame, steady engineer composure, readable five-finger grip")
    (:composition "diagonal cab framing, character lower left, throttle arc center-right, headlamp ring upper right, masthead layered behind torso"))

   ((:color-theme "orbit silver, nebula lilac, cold brass, zero-g ivory, soft cyan rim")
    (:secondary "clockwork orbital lift capsule interior, polished brass frame, soft nebula glow, sterile editorial silence")
    (:background "planet curve and star mist beyond capsule window, lilac nebula haze, minimal orbital rail line, deep space negative space")
    (:outfit-design "steampunk orbital courier couture, silver-white flight bodice, brass joint panels, lilac velvet harness ribbons, minimal pressure seals")
    (:thematic-symbol "brass orbital ring, star-chart dial, capsule hatch wheel, copper antenna arc, sparse meteor charm")
    (:evolution-strategy "gear-arc geometry evolves into orbital ring-curve language, hatch circles echo braid loops, panel rhythm maps across suit and capsule shell, graphic design fusion only, not physical mutation")
    (:action "floating calm stance inside capsule, one hand touching brass orbital ring, twin braids drifting softly, weightless elegance")
    (:composition "centered ring portal behind character, body offset left third, starfield upper negative space, balanced orbital asymmetry"))

   ((:color-theme "sea glass teal, bell bronze, rope cream, abyss navy, pearl foam")
    (:secondary "victorian diving bell chamber interior, round glass bell frame, sparse brass bolts, submerged editorial silence")
    (:background "underwater reef silhouettes beyond bell glass, sea-glass glow, minimal bubble trails, deep aqua negative space")
    (:outfit-design "steampunk diving scholar couture, bronze bell-collar dress panels, teal velvet bodice, cream rope-trim sleeves, minimal bolt accents")
    (:thematic-symbol "brass diving bell frame, copper air-hose coil, round depth gauge, single anchor charm, sparse kelp ribbon accent")
    (:evolution-strategy "gear-arc geometry evolves into diving-bell curve language, bolt rings echo loop motif, rope lines connect outfit and bell frame, graphic design fusion only, not physical mutation")
    (:action "standing inside bell chamber, one hand on brass depth gauge, serene underwater attentiveness, stable hand pose")
    (:composition "giant bell-glass circle center, character left, depth gauge lower right, masthead behind shoulders, luminous aqua breathing room"))

   ((:color-theme "canal jade, weathered oak, brass reed, mist lavender, parchment cream")
    (:secondary "narrowboat wheelhouse interior, lacquered wood panels, misty canal silence, minimal reed accents")
    (:background "misty canal water and stone arch beyond wheelhouse window, soft lavender haze, sparse mooring post, horizontal water negative space")
    (:outfit-design "steampunk canal navigator couture, jade velvet coat, oak-trim bodice, brass reed buttons, cream lace collar panels")
    (:thematic-symbol "brass canal winch, wooden tiller charm, rope coil ornament, copper lantern hook, sparse chart pin")
    (:evolution-strategy "gear-arc geometry evolves into canal-hull curve language, wood ribs echo braid loops, brass fittings align with window arches, graphic design fusion only, not physical mutation")
    (:action "one hand on wooden tiller charm mounted near wheel, other hand on wheelhouse frame, peaceful canal vigil")
    (:composition "horizontal canal vista lower half, character upper left, winch arc right, masthead behind head, misty upper negative space"))

   ((:color-theme "alpine snow, pine shadow green, cable brass, glacier cyan, rose dusk")
    (:secondary "alpine funicular cable-car booth interior, brass window frame, snow-muted editorial silence, minimal pine silhouettes")
    (:background "snowy mountain slope and glacier cliff beyond booth glass, glacier cyan haze, sparse cable line, cold sky negative space")
    (:outfit-design "steampunk alpine conductor couture, snow-white cropped jacket, pine-green velvet skirt panels, brass cable-trim collar, cyan ribbon harness")
    (:thematic-symbol "brass cable pulley, mountain ticket punch, round altimeter dial, copper ski-goggle charm, sparse edelweiss pin")
    (:evolution-strategy "gear-arc geometry evolves into cable-line curve language, pulley rings echo loop motif, slope diagonals map across outfit and booth frame, graphic design fusion only, not physical mutation")
    (:action "standing in cable-car booth, one hand holding brass ticket punch, quiet alpine composure, readable gesture")
    (:composition "steep diagonal mountain backdrop, character left, cable pulley center, ticket punch right, masthead behind, cold upper negative space"))

   ((:color-theme "sand ochre, burnt sienna, bronze sun, dust rose, copper mirage")
    (:secondary "desert sand-rail rover cockpit interior, bronze windshield frame, heat-muted editorial silence, minimal dune lines")
    (:background "dune sea and mirage shimmer beyond rover glass, burnt-sienna sunset, sparse rail trace, vast desert negative space")
    (:outfit-design "steampunk desert rover couture, ochre linen bodice, bronze shoulder guards, copper goggle scarf, dust-rose velvet sash")
    (:thematic-symbol "brass sand-rail gauge, copper canteen ring, sun-compass dial, leather glove charm, sparse dune-marker flag")
    (:evolution-strategy "gear-arc geometry evolves into dune-rail curve language, compass rings echo braid loops, sand-panel rhythm crosses outfit and cockpit frame, graphic design fusion only, not physical mutation")
    (:action "seated calm in rover cockpit, one hand on brass sand-rail gauge, other on steering ring, heat-hazed confidence")
    (:composition "wide desert horizon lower third, character upper left, steering ring center, compass dial right, masthead behind, hot sky negative space"))

   ((:color-theme "frost steel, iceberg cyan, navy brass, aurora violet, polar silver")
    (:secondary "arctic icebreaker bridge interior, frost brass console, polar editorial silence, minimal radar arcs")
    (:background "ice floe field and aurora veil beyond bridge window, iceberg cyan glow, sparse mast shadow, polar night negative space")
    (:outfit-design "steampunk icebreaker officer couture, frost-white bridge coat, navy velvet cuffs, brass radar-trim collar, aurora-violet scarf")
    (:thematic-symbol "brass radar sweep ring, ice-axe charm, copper bridge bell, round barometer dial, sparse signal flags")
    (:evolution-strategy "gear-arc geometry evolves into icebreaker hull-curve language, radar rings echo loop motif, frost panels align with bridge geometry, graphic design fusion only, not physical mutation")
    (:action "standing on icebreaker bridge, one hand on brass radar sweep ring, aurora-lit calm authority")
    (:composition "aurora curtain upper background, character left, radar ring center, bridge bell right, masthead behind, icy negative-space breathing"))

   ((:color-theme "velvet plum, tram brass, neon mist pink, lamp amber, midnight teal")
    (:secondary "velvet night-tram conductor booth interior, lacquered brass dashboard, neon-mist editorial silence, minimal city bokeh")
    (:background "rain-slick city street and neon bokeh beyond tram glass, midnight teal haze, sparse tram-line curve, urban night negative space")
    (:outfit-design "steampunk night-tram conductor couture, plum velvet uniform jacket, brass button rails, teal satin skirt panels, amber lamp-belt accent")
    (:thematic-symbol "brass ticket punch, tram bell lever, round fare dial, copper lantern charm, sparse route-map ribbon")
    (:evolution-strategy "gear-arc geometry evolves into tram-window curve language, fare dials echo braid loops, neon lines cross outfit and booth panels, graphic design fusion only, not physical mutation")
    (:action "standing in conductor booth, one hand on tram bell lever, other holding route-map ribbon, urban night poise")
    (:composition "vertical tram-window frame center, character left, bell lever right, neon bokeh upper negative space, masthead behind"))

   ((:color-theme "ferry teal, paddle brass, river mist, cedar brown, lantern gold")
    (:secondary "steam paddle ferry bridge interior, polished helm console, river-mist editorial silence, minimal paddle shadows")
    (:background "wide river bend and paddle spray beyond ferry glass, teal mist haze, sparse pier lamps, horizontal river negative space")
    (:outfit-design "steampunk ferry pilot couture, teal velvet jacket, brass paddle-button trim, cedar-brown skirt panels, lantern-gold neck scarf")
    (:thematic-symbol "brass paddle-wheel model, river bell pull, copper helm spoke, round tide clock, sparse mooring rope")
    (:evolution-strategy "gear-arc geometry evolves into paddle-wheel curve language, tide rings echo braid loops, wood-and-brass panels align across outfit and ferry bridge, graphic design fusion only, not physical mutation")
    (:action "standing at ferry helm console, one hand on paddle-wheel model, other on bridge rail, calm river authority")
    (:composition "paddle-wheel silhouette center-right, character left, river vista lower third, masthead behind upper torso, misty horizontal breathing room"))))