(in-package #:prompt-universe)

(defexpansion-plan dessert-jelly-flavor-10
  (:intent "ten fruit-flavor variants of anime prop jelly while preserving material control")
  (:seed "prop-design/GOLDEN-MANGO-JELLY")
  (:preserve :anime-material-override :negative-boundary :composition)
  (:variant-axes
   (:required :color-theme :theme-anchor :accessory-set)
   (:recommended :scene-shell)
   (:theme-anchor-keys :flavor :object-design :subtitle)
   (:accessory-keys :top-garnish))
  (:mutations
   ((:flavor "Fresh Apple")
    (:subtitle "Apple Jelly")
    (:color-theme "soft apple red, warm ivory, mint green, champagne gold, delicate prism accents")
    (:object-design "small apple cubes suspended inside cloudy translucent apple jelly")
    (:top-garnish "single apple blossom petal, one green leaf, casual asymmetrical placement"))
   ((:flavor "Wild Cherry")
    (:subtitle "Cherry Jelly")
    (:color-theme "deep cherry red, warm ivory, soft rose pink, champagne gold, delicate prism accents")
    (:object-design "small cherry halves suspended inside cloudy translucent cherry jelly")
    (:top-garnish "single cherry blossom, one mint leaf, casual asymmetrical placement"))
   ((:flavor "Summer Strawberry")
    (:subtitle "Strawberry Jelly")
    (:color-theme "soft strawberry pink, warm ivory, dusty mint green, champagne gold, delicate prism accents")
    (:object-design "strawberry fragments suspended inside cloudy translucent strawberry jelly")
    (:top-garnish "single small strawberry, two mint leaves, casual asymmetrical placement"))
   ((:flavor "Blueberry")
    (:subtitle "Blueberry Jelly")
    (:color-theme "dusty blueberry purple, warm ivory, soft lavender, champagne gold, delicate prism accents")
    (:object-design "small blueberries suspended inside cloudy translucent blueberry jelly")
    (:top-garnish "single blueberry cluster accent, one mint leaf, casual asymmetrical placement"))
   ((:flavor "Golden Peach")
    (:subtitle "Peach Jelly")
    (:color-theme "golden peach orange, warm ivory, soft blush pink, champagne gold, delicate prism accents")
    (:object-design "small peach cubes suspended inside cloudy translucent peach jelly")
    (:top-garnish "single peach blossom, one mint leaf, casual asymmetrical placement"))
   ((:flavor "Honey Yuzu")
    (:subtitle "Honey Yuzu Jelly")
    (:color-theme "bright yuzu yellow, honey amber, pale citrus cream, champagne gold, delicate prism accents")
    (:object-design "thin yuzu peel spirals and citrus pearls suspended inside cloudy honey-yuzu jelly")
    (:top-garnish "single yuzu zest curl, one mint leaf, casual asymmetrical placement"))
   ((:flavor "Lychee")
    (:subtitle "Lychee Jelly")
    (:color-theme "pale lychee pink, warm ivory, soft pearl white, champagne gold, delicate prism accents")
    (:object-design "lychee fruit pieces suspended inside cloudy translucent lychee jelly")
    (:top-garnish "single lychee shell accent, one mint leaf, casual asymmetrical placement"))
   ((:flavor "Kyoho Grape")
    (:subtitle "Grape Jelly")
    (:color-theme "deep grape violet, warm ivory, dusty plum, champagne gold, delicate prism accents")
    (:object-design "small grape clusters suspended inside cloudy translucent grape jelly")
    (:top-garnish "single grape leaf, casual asymmetrical placement"))
   ((:flavor "Kiwi")
    (:subtitle "Kiwi Jelly")
    (:color-theme "bright kiwi green, warm ivory, soft lime, champagne gold, delicate prism accents")
    (:object-design "kiwi slices suspended inside cloudy translucent kiwi jelly")
    (:top-garnish "single kiwi seed accent pattern, one mint leaf, casual asymmetrical placement"))
   ((:flavor "Pineapple")
    (:subtitle "Pineapple Jelly")
    (:color-theme "golden pineapple yellow, warm ivory, soft leaf green, champagne gold, delicate prism accents")
    (:object-design "small pineapple cubes suspended inside cloudy translucent pineapple jelly")
    (:top-garnish "single pineapple crown leaf, casual asymmetrical placement"))))