(in-package #:prompt-universe)

(defexpansion-plan platform-last-light-uniform-10
  (:intent "ten cinematic photorealistic variants swapping professional uniforms and service-transit scenes while preserving film-still identity")
  (:source platform-last-light)
  (:preserve :primary :title :facial-traits :camera :quality :negative :hair-parameter)
  (:variant-axes
   (:required :color-theme :theme-anchor :accessory-set)
   (:recommended :scene-shell :outfit-design :evolution-strategy :action :composition)
   (:theme-anchor-keys :secondary :background :story-background)
   (:accessory-keys :thematic-symbol :accessory-design))
  (:mutations
   ((:subtitle "Gate Dawn")
    (:color-theme "dawn pearl grey, soft sky cyan, brushed aluminum, muted navy uniform, pale rose horizon")
    (:secondary "empty airport boarding gate interior, floor-to-ceiling glass wall, sparse gate seating, quiet pre-flight silence")
    (:background "vacant jet bridge corridor and pale dawn sky beyond glass, cool cyan haze, minimal runway bokeh, wide horizontal negative space")
    (:story-background "a young flight attendant stands alone at an empty boarding gate at dawn, first departure light approaching in the distance, quiet professional composure before the morning rush")
    (:outfit-design "airline cabin-crew uniform, tailored navy blazer with wing pin, pleated pencil skirt, silk neck scarf, polished low heels, crisp airline-service silhouette")
    (:thematic-symbol "boarding-pass sleeve, retractable belt stanchion, distant aircraft nose light, gate number plaque without readable text, rolling carry-on silhouette")
    (:accessory-design "structured flight-service tote at side, minimal wing-pin glint, no airline logo markings, understated crew accessories")
    (:evolution-strategy "runway line geometry echoes uniform seam lines, glass-panel grid aligns with blazer button rhythm, horizon light band maps across scarf and gate frame, environmental fusion only, not body mutation")
    (:action "standing at gate window, one hand holding boarding-pass sleeve, gaze toward distant aircraft light, upright crew posture, scarf settling from ventilation breeze")
    (:composition "character left third, glass corridor center, aircraft light far right depth, long horizontal dawn sky upper negative space, cinematic gate asymmetry")
    (:lighting "cool dawn skylight through glass, soft aluminum gate reflections, distant warm aircraft light rim on scarf edge, gentle interior fill")
    (:tertiary "tailored airline-blazer wool, matte pencil-skirt creases, brushed aluminum gate frame, tempered glass panel reflections, broad low-frequency transitions, suppressed micro-noise")
    (:quaternary "distant aircraft nose-light bloom as secondary accent only, soft gate-lamp rim glow, subtle dawn haze, minimal lens flare, controlled atmospheric diffusion")
    (:negative-space-guidance "large open dawn sky beyond glass, minimal gate furniture density, strong silhouette isolation, single-subject visual dominance, controlled empty-space breathing, cinematic gate emptiness"))

   ((:subtitle "Harbor Watch")
    (:color-theme "maritime white, rope cream, deep ocean navy, weathered teak, brass compass gold")
    (:secondary "naval academy training ship deck at golden hour, polished railing, sparse rigging shadows, open-sea editorial silence")
    (:background "harbor water and distant lighthouse beyond ship rail, golden-hour haze, minimal buoy silhouettes, expansive sea negative space")
    (:story-background "a young sailor cadet in dress uniform stands alone on a quiet training-ship deck at golden hour, harbor watch before evening muster, sea wind lifting neckerchief edge")
    (:outfit-design "naval academy dress uniform, crisp white middy blouse, navy neckerchief, pleated navy skirt, brass anchor buttons, polished deck shoes, disciplined maritime silhouette")
    (:thematic-symbol "coiled mooring rope, brass compass on lanyard, ship bell silhouette, distant lighthouse beam, worn deck plank line")
    (:accessory-design "leather logbook folio at hip, minimal brass compass lanyard, no naval insignia text, understated cadet accessories")
    (:evolution-strategy "deck plank lines echo uniform pleat rhythm, railing curve language aligns with neckerchief fold geometry, lighthouse beam band crosses collar and horizon, environmental fusion only, not body mutation")
    (:action "standing at ship railing, one hand on coiled rope, other resting on logbook folio, calm harbor watch gaze toward lighthouse")
    (:composition "ship railing diagonal lower frame, character left, lighthouse far center-right, open sea upper negative space, golden maritime asymmetry")
    (:lighting "warm golden-hour sun from port side, cool sea bounce fill, lighthouse beam as distant rim accent, natural deck shadow falloff")
    (:tertiary "crisp middy-blouse cotton, navy neckerchief fold, weathered teak deck grain, polished brass railing patina, broad low-frequency transitions, suppressed micro-noise")
    (:quaternary "distant lighthouse beam as secondary accent only, soft golden-hour rim on neckerchief edge, subtle sea haze, minimal spray mist, controlled atmospheric diffusion")
    (:negative-space-guidance "large open sea horizon beyond rail, minimal deck clutter density, strong silhouette isolation, single-subject visual dominance, controlled empty-space breathing, maritime editorial emptiness"))

   ((:subtitle "Lobby Dusk")
    (:color-theme "art-deco champagne, onyx black, warm lobby amber, marble ivory, muted gold trim")
    (:secondary "art-deco hotel lobby interior at dusk, polished marble floor, sparse velvet seating, luxury hospitality silence")
    (:background "grand lobby columns and revolving door glow beyond concierge desk, amber dusk haze, minimal chandelier bokeh, vertical architectural negative space")
    (:story-background "a young concierge stands alone behind an empty hotel desk at dusk, last guest departed, lobby lights warming for evening service")
    (:outfit-design "luxury hotel concierge uniform, tailored black blazer, champagne satin blouse, knee-length pencil skirt, gold-trim lapels, polished court shoes, refined hospitality silhouette")
    (:thematic-symbol "brass desk bell, leather key-card folio, art-deco table lamp, revolving-door light halo, marble column edge")
    (:accessory-design "slim leather key folio in hand, minimal gold lapel pin, no hotel brand markings, understated concierge accessories")
    (:evolution-strategy "marble veining lines echo blazer lapel geometry, column vertical rhythm maps across skirt seam and lobby frame, amber lamp band aligns with gold trim accents, environmental fusion only, not body mutation")
    (:action "standing behind concierge desk, one hand on brass desk bell, other holding key folio, poised evening-service attentiveness")
    (:composition "desk foreground lower third, character center-left, revolving-door glow upper right, chandelier bokeh upper negative space, art-deco vertical framing")
    (:lighting "warm amber lobby lamps, cool dusk spill through revolving door, soft marble bounce fill, controlled gold-trim highlights")
    (:tertiary "tailored black-blazer wool, champagne satin blouse sheen, polished marble floor veining, art-deco brass lamp patina, broad low-frequency transitions, suppressed micro-noise")
    (:quaternary "revolving-door light halo as secondary accent only, soft chandelier bokeh rim, subtle dusk haze, minimal lens flare, controlled atmospheric diffusion")
    (:negative-space-guidance "large vertical lobby void above columns, minimal seating density, strong silhouette isolation, single-subject visual dominance, controlled empty-space breathing, luxury hospitality emptiness"))

   ((:subtitle "Gallery Morning")
    (:color-theme "gallery bone white, soft sage green, charcoal grey, warm oak, muted brass")
    (:secondary "empty museum gallery interior at morning open, white walls, sparse bench seating, curatorial editorial silence")
    (:background "large framed canvases and polished oak floor beyond docent station, soft morning window light, minimal sculpture pedestal, clean gallery negative space")
    (:story-background "a young museum docent in uniform stands alone in an empty gallery at morning open, first light entering before visitors arrive, quiet reverence for the collection")
    (:outfit-design "museum docent uniform, sage-green tailored blazer, cream blouse, charcoal pencil skirt, muted brass name-badge plate without readable text, low heel pumps, scholarly service silhouette")
    (:thematic-symbol "gallery guide wand, leather exhibition pamphlet folio, oak bench edge, framed canvas corner, soft window light shaft")
    (:accessory-design "exhibition pamphlet folio at side, minimal brass badge plate, no museum logo text, understated docent accessories")
    (:evolution-strategy "frame-edge geometry echoes blazer lapel lines, oak floor plank rhythm maps across skirt pleats and gallery baseboard, window light band crosses blouse and wall plane, environmental fusion only, not body mutation")
    (:action "standing beside empty bench, one hand holding guide wand low, other on pamphlet folio, calm curatorial gaze toward framed canvas")
    (:composition "large canvas mass right third, character left, window light shaft center, oak floor lower breathing room, gallery morning asymmetry")
    (:lighting "soft morning window sidelight, cool white-wall bounce, muted brass accent highlights, gentle gallery shadow gradients")
    (:tertiary "sage-green blazer wool, cream blouse cotton, polished oak floor grain, white-gallery wall matte, broad low-frequency transitions, suppressed micro-noise")
    (:quaternary "window light shaft as secondary accent only, soft canvas-edge rim glow, subtle morning haze, minimal lens flare, controlled atmospheric diffusion")
    (:negative-space-guidance "large white-wall breathing regions, minimal pedestal density, strong silhouette isolation, single-subject visual dominance, controlled empty-space breathing, curatorial gallery emptiness"))

   ((:subtitle "Reading Hall")
    (:color-theme "library walnut brown, parchment cream, dusty burgundy, brass lamp amber, slate blue")
    (:secondary "grand library reading hall interior, tall walnut shelves, sparse reading tables, scholarly editorial silence")
    (:background "vaulted bookshelf walls and arched windows beyond reading aisle, parchment-toned morning haze, minimal ladder silhouette, vertical literary negative space")
    (:story-background "a young librarian in uniform stands alone in a vast reading hall before opening hour, morning light crossing empty tables, quiet guardianship of the stacks")
    (:outfit-design "classic librarian service uniform, burgundy cardigan over cream blouse, tailored slate skirt, walnut-brown belt, low heel oxfords, modest academic silhouette")
    (:thematic-symbol "hardcover book stack, brass reading-lamp arm, wooden library ladder, arched window frame, ribbon bookmark accent")
    (:accessory-design "single hardcover book held at chest, minimal ribbon bookmark, no library logo text, understated librarian accessories")
    (:evolution-strategy "bookshelf horizontal lines echo cardigan hem geometry, arch curve language aligns with window and belt line, lamp amber band maps across blouse and table edge, environmental fusion only, not body mutation")
    (:action "standing between reading tables, one hand on book stack, other adjusting ribbon bookmark, serene pre-open attentiveness")
    (:composition "tall shelves left and right framing, character center-left, arched window upper center, empty tables lower negative space, reading-hall vertical depth")
    (:lighting "warm brass reading-lamp pools, cool arched-window fill, walnut shelf bounce warmth, soft academic shadow control")
    (:tertiary "burgundy cardigan knit, cream blouse cotton, walnut shelf grain, parchment-toned table surface, broad low-frequency transitions, suppressed micro-noise")
    (:quaternary "arched-window light band as secondary accent only, soft brass-lamp rim glow, subtle dust-mote haze, minimal lens flare, controlled atmospheric diffusion")
    (:negative-space-guidance "large vaulted aisle negative space, minimal table density, strong silhouette isolation, single-subject visual dominance, controlled empty-space breathing, scholarly hall emptiness"))

   ((:subtitle "Cafe Open")
    (:color-theme "espresso brown, steamed milk cream, copper machine glow, mint apron accent, warm bakery amber")
    (:secondary "vintage cafe interior before opening, copper espresso machine, sparse counter stools, morning bakery silence")
    (:background "chalkboard menu silhouette without readable text and street window beyond counter, warm bakery amber haze, minimal pastry case glow, cozy interior negative space")
    (:story-background "a young barista in service uniform stands alone behind a quiet cafe counter before opening, first espresso machine heat warming the room, calm prep before morning service")
    (:outfit-design "cafe service uniform, cream blouse, espresso-brown apron with mint trim, dark tailored trousers, copper-button fastenings, comfortable service shoes, approachable barista silhouette")
    (:thematic-symbol "ceramic pour-over set, copper tamper, steam wand silhouette, pastry tongs, chalkboard edge without legible text")
    (:accessory-design "folded service towel at waist, minimal mint apron tie, no cafe brand markings, understated barista accessories")
    (:evolution-strategy "counter edge lines echo apron hem geometry, copper machine curve language aligns with steam wand and button rhythm, bakery amber band crosses apron and window frame, environmental fusion only, not body mutation")
    (:action "standing behind counter, one hand on pour-over set, other resting on copper tamper, focused pre-open preparation")
    (:composition "counter foreground lower half, character center-left, street window upper right, espresso machine copper mass right accent, cozy cafe asymmetry")
    (:lighting "warm bakery amber from street window, copper machine glow accent, cool interior shadow pockets, natural steam-haze softness")
    (:tertiary "espresso-brown apron canvas, cream blouse cotton, copper machine patina, matte counter laminate, broad low-frequency transitions, suppressed micro-noise")
    (:quaternary "copper espresso-machine glow as secondary accent only, soft steam-haze rim, subtle bakery warmth, minimal lens flare, controlled atmospheric diffusion")
    (:negative-space-guidance "large street-window glow region, minimal counter clutter density, strong silhouette isolation, single-subject visual dominance, controlled empty-space breathing, cozy cafe emptiness"))

   ((:subtitle "Postal Hour")
    (:color-theme "postal navy blue, vintage cream, rubber-stamp red, oak counter brown, brass scale gold")
    (:secondary "vintage post office interior, oak service counter, sparse sorting cubbies, civic editorial silence")
    (:background "brass postal scales and pigeonhole wall beyond counter, muted cream interior haze, minimal parcel shelf silhouettes, horizontal civic negative space")
    (:story-background "a young postal clerk in uniform stands alone behind a vintage post office counter at quiet hour, sorting trays ready before the midday rush, civic calm in still air")
    (:outfit-design "vintage postal clerk uniform, navy service jacket, cream blouse, matching navy skirt, brass button row, low heel pumps, modest civic-service silhouette")
    (:thematic-symbol "rubber stamp and ink pad, brass letter scale, parcel twine spool, oak counter edge, sorting pigeonhole grid")
    (:accessory-design "leather stamp pad tray at counter, minimal brass scale chain, no postal logo text, understated clerk accessories")
    (:evolution-strategy "pigeonhole grid geometry echoes uniform button rhythm, oak counter line maps across skirt hem and service desk, brass scale arc aligns with jacket lapel curve, environmental fusion only, not body mutation")
    (:action "standing behind postal counter, one hand on brass scale tray, other holding parcel twine spool, steady civic composure")
    (:composition "long counter horizontal lower third, character left, pigeonhole wall center-right, brass scale foreground accent, civic interior asymmetry")
    (:lighting "soft cream interior ambient, warm brass scale highlights, cool navy uniform shadow separation, muted window sidelight")
    (:tertiary "navy service-jacket wool, cream blouse cotton, oak counter grain, brass scale patina, broad low-frequency transitions, suppressed micro-noise")
    (:quaternary "brass scale gleam as secondary accent only, soft window sidelight rim, subtle interior haze, minimal lens flare, controlled atmospheric diffusion")
    (:negative-space-guidance "large pigeonhole wall breathing region, minimal counter clutter density, strong silhouette isolation, single-subject visual dominance, controlled empty-space breathing, civic postal emptiness"))

   ((:subtitle "Greenhouse Mist")
    (:color-theme "botanical fern green, humid glass white, terracotta clay, copper watering can, soft orchid lilac")
    (:secondary "victorian greenhouse conservatory interior, humid glass panels, sparse potting benches, botanical editorial silence")
    (:background "tropical fern silhouettes and misted glass roof beyond aisle, orchid lilac haze, minimal watering-can reflection, lush glass negative space")
    (:story-background "a young horticulturist in work uniform stands alone in a misted greenhouse at early morning, watering routine before visitors enter, humid calm among ferns")
    (:outfit-design "botanical garden work uniform, fern-green chore coat, cream shirt, terracotta apron panel, dark practical trousers, rubber garden clogs, functional horticulture silhouette")
    (:thematic-symbol "copper watering can, pruning shears on belt hook, terracotta pot stack, misted glass pane, orchid stem accent")
    (:accessory-design "leather pruning sheath at belt, minimal copper can handle wrap, no garden brand markings, understated horticulture accessories")
    (:evolution-strategy "glass-pane grid echoes chore-coat seam lines, pot-rim curve language aligns with apron panel and collar, mist band crosses glass roof and uniform hem, environmental fusion only, not body mutation")
    (:action "standing between potting benches, one hand on copper watering can, other touching fern frond gently, serene greenhouse attentiveness")
    (:composition "glass roof upper negative space, character left, fern mass right depth, potting bench lower foreground, humid conservatory asymmetry")
    (:lighting "diffused greenhouse skylight, humid mist softening highlights, copper can warm accent, cool fern-green bounce fill")
    (:tertiary "fern-green chore-coat canvas, terracotta apron clay, misted glass condensation, copper watering-can patina, broad low-frequency transitions, suppressed micro-noise")
    (:quaternary "orchid-lilac mist bloom as secondary accent only, soft glass-roof rim glow, subtle humidity haze, minimal water-droplet sparkle, controlled atmospheric diffusion")
    (:negative-space-guidance "large glass-roof sky region, minimal bench clutter density, strong silhouette isolation, single-subject visual dominance, controlled empty-space breathing, botanical conservatory emptiness"))

   ((:subtitle "Hall Prelude")
    (:color-theme "velvet burgundy, concert hall black, gilt brass, chandelier crystal, muted stage amber")
    (:secondary "empty concert hall lobby interior before performance, velvet rope stanchions, sparse marble flooring, ceremonial editorial silence")
    (:background "grand staircase and chandelier beyond lobby velvet ropes, muted stage-amber glow from auditorium doors, minimal poster frame silhouettes without readable text, vertical gala negative space")
    (:story-background "a young usher in formal uniform stands alone in an empty concert hall lobby before the audience arrives, velvet ropes still closed, anticipatory hush before prelude")
    (:outfit-design "concert hall usher uniform, black tailored jacket, burgundy waistcoat, cream dress shirt, black midi skirt, gilt brass buttons, polished formal flats, ceremonial service silhouette")
    (:thematic-symbol "velvet rope stanchion, gilt program tray, chandelier crystal edge, auditorium door light spill, marble stair curve")
    (:accessory-design "folded programs on gilt tray, minimal brass button glint, no venue logo text, understated usher accessories")
    (:evolution-strategy "stair curve geometry echoes waistcoat lapel line, chandelier radial pattern maps across button row and marble floor, auditorium amber band crosses skirt hem and door frame, environmental fusion only, not body mutation")
    (:action "standing beside velvet rope stanchion, one hand on gilt program tray, other resting on stanchion post, formal pre-show composure")
    (:composition "grand staircase upper background, character lower left, chandelier center-top, auditorium glow far right, lobby vertical gala framing")
    (:lighting "warm chandelier crystal spill, cool marble bounce, muted auditorium amber rim on jacket edge, controlled lobby shadow depth")
    (:tertiary "black tailored-jacket wool, burgundy waistcoat satin, polished marble floor veining, gilt brass button gleam, broad low-frequency transitions, suppressed micro-noise")
    (:quaternary "chandelier crystal spill as secondary accent only, soft auditorium-door amber rim, subtle gala haze, minimal lens flare, controlled atmospheric diffusion")
    (:negative-space-guidance "large staircase void above lobby, minimal stanchion density, strong silhouette isolation, single-subject visual dominance, controlled empty-space breathing, ceremonial hall emptiness"))

   ((:subtitle "Terminal Night")
    (:color-theme "terminal concrete grey, neon wayfinding cyan, rain-slick charcoal, transit navy, sodium amber")
    (:secondary "empty late-night bus terminal concourse, concrete columns, sparse plastic seating, urban transit silence")
    (:background "rain-slick arrival lanes and sodium streetlights beyond terminal glass, neon wayfinding glow without readable text, minimal bus silhouette, urban night negative space")
    (:story-background "a young transit service officer in uniform stands alone in an empty bus terminal late at night, last departure lane quiet under rain, urban solitude before final route")
    (:outfit-design "municipal transit officer uniform, navy weather-resistant jacket, reflective trim bands, charcoal service trousers, transit cap, practical duty boots, authoritative transit silhouette")
    (:thematic-symbol "handheld radio silhouette, route schedule board without legible text, rain-streaked terminal glass, distant bus headlight, plastic seat row")
    (:accessory-design "duty radio at belt, minimal reflective trim catchlight, no transit authority logo text, understated officer accessories")
    (:evolution-strategy "concourse column rhythm echoes jacket seam lines, route-board grid aligns with reflective trim bands, bus headlight band crosses cap brim and glass frame, environmental fusion only, not body mutation")
    (:action "standing under terminal canopy, one hand on duty radio, gaze toward distant bus headlight through rain glass, steady night-shift vigilance")
    (:composition "rain-streaked glass center, character left, bus headlight far depth right, concrete column vertical framing, neon cyan upper accent negative space")
    (:lighting "cool neon wayfinding spill, warm sodium streetlight through rain glass, reflective trim edge highlights, wet concrete bounce")
    (:tertiary "navy weather-resistant jacket fabric, reflective trim bands, rain-streaked terminal glass, wet concrete sheen, broad low-frequency transitions, suppressed micro-noise")
    (:quaternary "distant bus headlight bloom as secondary accent only, neon wayfinding rim spill, subtle rain haze, minimal water streak glare, controlled atmospheric diffusion")
    (:negative-space-guidance "large rain-glass corridor region, minimal seating density, strong silhouette isolation, single-subject visual dominance, controlled empty-space breathing, urban transit night emptiness"))))